### ISSUE TITLE
Data entry flow and form processing updates

### ISSUE THREAD

**Issue by pld** [onaio/tally-ho#176]
This issue collects the first tranche of data entry and form processing updates. This includes only slight modifications to the data entry process.

* [x] [Combine QC and audit](https://github.com/onaio/tally-ho/issues/177)
* [x] [Updated clearance process](https://github.com/onaio/tally-ho/issues/178)
* [x] [Updated audit process](https://github.com/onaio/tally-ho/issues/179)

<img width="367" alt="data entry flow" src="https://user-images.githubusercontent.com/50706/45663779-e1fb1700-bb10-11e8-9628-48ed15f4735a.png">
