### ISSUE TITLE
Duplicate form tracking

### ISSUE THREAD

**Issue by pld** [onaio/tally-ho#185]
*Status: This functionality partially exists*

Done:
* Where two forms are attempted to be in-taken into the system against the same centre and station and race, the issue should be raised to clearance as “duplicate forms” and both forms should be electronically passed to the clearance stage. The screen shall display the entered form details, including the barcode.
* Neither form will be able to progress further through the system. If the first form is attempted to be entered at any of the subsequent stages of the data entry process, the system will inform the user that the form is classified as a duplicate form and is to be passed to clearance section.

To do:
* [x] 1. The clearance section may access a list of duplicate cases on a duplicate case monitoring tool, which lists the details including the expected location of the form shall be listed.
* [x] 2. The staff will have the option of choosing to reset one or both of the forms.
* [x] 3. Archived forms require additional reviews prior to resetting.

**Comment by pld** [comment]
Notes on this:

(1)
* right now these are viewable in the clearance list
* what is "expected location"? if that's state the system doesn't store that in an easy to access way, because the state is reset to `clearance` when in encounters the duplicate

(3)
* related to (1), the system won't know that the form had been archived, so won't know which to give additional review
* need to clarify what "additional review" means

**Comment by JohnMwashuma** [comment]
Notes on the above issues to clarify:

1. what is "expected location"?
  `In the case there are duplicate forms, the first form may already have started to be processed before the second form is attempted at intake. In this case, we would need to track down the second form and retrieve it to clearance. Accordingly, knowing what stage the form is, is important.`
2. clarify what "additional review" means
`Prior to accepting the reset, the system should flag if the constituency of the form has been marked as released`

Going to create two issues:
1. Adding the expected location of the form in clearance section i.e `previous form location before resetting to clearance`. This means will have to save form state/location before sending it to clearance.
2. Add a flag to check if the constituency of the form has been marked as released when resetting an archived form.

**Comment by JohnMwashuma** [comment]
Remove blocked label since the issue is now clear.

**Comment by JohnMwashuma** [comment]
The current state of the system prevents creation of form duplicates. The areas which could have lead to duplicate forms were when creating a new form from the clearance section which has now been completely fixed by this issue #213  pr https://github.com/onaio/tally-ho/pull/214 and the other place was during form intake which currently does not allow for this.

That said, it does beg the question of whether we currently need to track form duplicates. @pld @akahure  your opinion on this please.

**Comment by JohnMwashuma** [comment]
> The current state of the system prevents creation of form duplicates. The areas which could have lead to duplicate forms were when creating a new form from the clearance section which has now been completely fixed by this issue #213 pr #214 and the other place was during form intake which currently does not allow for this.
> 
> That said, it does beg the question of whether we currently need to track form duplicates. @pld @akahure your opinion on this please.

After further investigation i have realised i had a wrong understanding of how form duplicates happen. So it's still a problem that needs tracking. @pld and @akahure Don't respond to this, my bad.

**Comment by pld** [comment]
k, cool, no worries

**Comment by JohnMwashuma** [comment]
Closing this issue since related issues which were pending have been closed.
