### ISSUE TITLE
Duplicate results tracking - based on ballot

### ISSUE THREAD

**Issue by pld** [onaio/tally-ho#186]
As an election manager or administrator I want to be able to review suspicious result forms.

* [x] Create a new page called "Duplicate Result Tracking"
* [x] Add a new column `duplicate_reviewed` to results forms, default False
* [x] This page shows a list (table) sorted by race/ballot of results forms for which there are more than 1 result form in the same race with the same number of votes per candidate, and the `duplicate_reviewed` column is false
* [x] The actions column in this table has a "view" button that leads to detailed view of all the duplicate results forms for the race, i.e. all results forms in the same race lead to the same detailed view page
  * [x] the detailed view page shows a hyper-linked list at top (not table) at top with all the results forms and a "send to clearance" button, which moves that form to clearance and returns the user to the main list page if there were 2 duplicate forms, or stays here and shows the remaining duplicate forms if there were more than 2 result forms
  * [x] the first results form is selected and below it shows that first full results form content
  * [x] at top there is a "send all to clearance" button, that sends all results forms (send them to the clearance state) and sets `duplicate_reviewed` to True, sets a notification message and returns the user to the main list page
  * [x] at top there is a "mark as reviewed and accepted" button that sets the `duplicate_reviewed` column to True for the result form, sets a notification message, and returns the user to the main list page

* [x] set `duplicate_reviewed` to False, whenever a form is set to intake or un-submitted, data entry 1, data entry 2, or corrections

---

Reference text from ToR:

*Status: This functionality partially exists*

Where two or more stations running the same race have the same voters cast per candidate, they will be displayed on a duplicate monitoring screen.

* It will be possible to click though to view the results associated with the forms.
* The staff will have the option of choosing to reset one or both forms.
* Archived forms require additional reviews prior to resetting.
* The results listed as duplicated can be marked as ‘reviewed and accepted’.

**Comment by pld** [comment]
Assigning to myself for research and clarification

**Comment by pld** [comment]
@JohnMwashuma I rewrote this issue as a set of tasks

@mrajayp can you review this more detailed description?

**Comment by akahure** [comment]
>  at top there is a "mark as reviewed and accepted" button that sets the "duplicate_reviewed" column to true for the result form, sets a notification message, and returns the user to the main list page
Does this mean that we will accept the results in the final tally ? @pld

**Comment by pld** [comment]
Not necessarily, since the result form could get flagged somewhere else in the process, but it does mean that this will not block it from going into the final tally

**Comment by pld** [comment]
@mrajayp rewrote this to not worry about archived and send forms to clearance as reset, since this can only be used by super-admins
