### ISSUE TITLE
Topology updates

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#226]
Tally system topology updates.

- [ ] [Multiple data entry channels](https://github.com/onaio/tally-ho/issues/222)
- [ ] [Data Exporting from a Data Entry Centre](https://github.com/onaio/tally-ho/issues/223)
- [ ] [ Consolidated Results and Monitoring National Consolidation Serve](https://github.com/onaio/tally-ho/issues/224)
- [ ] [ Public Results Website and tools](https://github.com/onaio/tally-ho/issues/225)
