### ISSUE TITLE
Staff performance and metrics

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#243]
### Current requirement functionality
---
*This functionality does not exist in the current software.*
### User Story
---
- The system should be able to track the performance of individual data entry clerks and sections.
- It should track for output, speed and accuracy.
- It should track the performance of sections and different data entry centers.

Tracking shall be both overall and over time. The metrics shall be accessible on reports, with graphs, which shall auto-refresh

### Proposed Implementation according to the workshop meeting notes
---
Items to be tracked:

- Staff daily completion rate for each group (DE1, DE2, etc)
    - Per person, calculate number of forms completed per N (hour):
       - Or average over the day
       - Total number of forms processed that hour by that group
   - For each user:
      - Show the number of completed forms
      - DO NOT Show whether they have an active form
      - DO NOT show which form that is active
      - DO NOT Show whether they are logged in
- Set user session timeout to X value, make sure admin docs describe how to modify this value
- Per user (supervisor clerk) show supervisor approval rate for forms after ‘Audit’ 
   - Number of forms approved by supervisor / number of forms sent for review by supervisor
- Tally Admin will have access to view the staff metrics. No one else.
- Accuracy: track what is going to correction
  - Determine what was chosen in corrections and see which data entry this corresponds with, that means that the error was in the other data entry.
  - Calculate number of errors (error forms).
  - Calculate percentage of errors (error forms / total forms processed).
  - Table with ordered list of users sorted by percentage of error.

### Required Changes
---

- [x]  Restrict staff metrics screen to Tally Admin only.

- [x] Track how long a form took to pass through the different states (DE1, DE2, etc) and which users did the entry. #251

- [x]  Build out tables of users for each group (DE1, DE2, etc), these tables will have the following columns: #251

   - Username.
   - Number of forms processed by the user.
   - Number of forms processed per N (hour) by that user.

- [x]  Implement a way to set user timeout from the GUI. #252

- [x]  Build out a table for all audit supervisor clerks. #253

  - supervisor clerk name.
  - number of forms approved.
  - number of forms processed.
  - supervisor approval rate: number of forms approved by supervisor / number of forms sent for review by supervisor.

- [ ]  `Accuracy: track what is going to correction`: #254

    - track user, data entry stage and errors before storing form corrections.
    - Calculate percentage of errors per user (error forms by the user/ total forms processed by the user).
  - Build a table with ordered list of users sorted by percentage of error.

**Comment by pld** [comment]
- This isn't just DE1 and DE2, also corrections and quality control, (aside, are those being combined into 1 step?)
- Timestamps and user assignments should already be in there, but maybe we want to accumulate these instead of having to generate them from data
- We can remove filter, just showing
- Need a mock-up for this

**Comment by JohnMwashuma** [comment]
@pld I have updated the issue accordingly, please have a look. And yes, we are considering all user groups.

**Comment by pld** [comment]
@JohnMwashuma this looks great, thank you for the detailed breakdown.

This is a big issue, I think we should either split out the top level check-boxes into separate issues or have separate PRs for each checkbox.

What do you think?

**Comment by JohnMwashuma** [comment]
@pld I agree let's split it into different issues.
