### ISSUE TITLE
Internal reporting of progress and results

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#244]
### Current requirement functionality
---
*This functionality partially exists in the current software.*
### User Story
---
This requirement outlines how internal reporting will provide insight on the ongoing data collection and review progress and the final results being tallied. 

### Proposed Implementation
---
- Define reports downloadable formats:
  - Add JSON download, array of results with each row a k/v pair
  - Allow specific users to download whole database through the UI (to be agreed)
- Report of turnout split by gender country-wide
  - Split again by sub-constituency
  - Maybe split again by center or station
- Get list of stations (maybe centers too) based on percent completion, where percent completion can be set by the admin as a filter E.g. progress report (number intaken) split by station/center?
- In office progress
  - Add sum of all the valid votes in the reconciliation forms for a specific office
  - Maybe do this more general, sum of FIELD in reconciliation form for another aggregated FIELD
     - Can we base this on the Libya Votes website?
- In Audit list
  - Filter by the quarantine trigger that moved this form to audit
- Images for presentation(To be discussed/Investigated) 
   - Look into embedding these in the website and present them on the website as well as make downloadable for embedding in presentation and reports
   - Look into building out images from the existing results
- Nice to have an access report for only user
- Database backups(Clarification needed)
  - Replica of production database to N (2 in the previous election setup, guarantee 1 before confirm) separate physical machines
  - Create dump from replica every N (1 in the previous election setup) hours from 1 replica, so that production performance isn’t degrade
  - Test recovery of database backup at some time frequency

### Required Changes
---

- [ ] Add json export option for results reports: https://github.com/onaio/tally-ho/issues/274

  - array of results with each row a k/v pair.

- [ ] Add a turnout report module which will be a table displaying https://github.com/onaio/tally-ho/issues/273:
  - Show total number of voters that have voted at the moment.
     - Split again by sub-constituency
     - Maybe split again by center or station
- [ ]  Update the office progress report module https://github.com/onaio/tally-ho/issues/272

  - Rename this module name to something more generic because offices progress report is one of the reports being displayed.

  - Add a new column in the office table that will display sum of all the valid votes in the reconciliation forms for a specific office

  - Create a another progress report that will show form progress per station, should display the number of forms in particular stages and calculate percentage, will be very similar to the centers report.
- [x] Update audit list report to include: https://github.com/onaio/tally-ho/issues/270

   - Filter by the quarantine trigger that moved this form to audit
- Nice to have an access report for only user

**Comment by pld** [comment]
1. Turnout report
  - yes, this can be a table
  - for sub-cons, center, station, will you see all these broken down and filter which ones show up? not sure filter is necessary vs showing the details
  - this needs a UI mock-up
2. Center/station completion
  - doesn't this exist already?
  - for setting percent, need more details here, maybe from them
3. Office report
  - how does this fit into the hierarchy, is an office multiple sub-cons?
4. Nice to access for only user
  - what does this mean? like a new "reports" user?

If think we should combine (2) and (3) and split that off into a progress reports issue. We already have a sub-cons progress page, right? can we make the office/center/station progress pages extension of the existing sub-cons one? that's how the `sum(FIELD1) grouped by FIELD2` would work with `FIELD1` usually votes and `FIELD2` from the set of sub-con/office/center/station. There current code for sub-cons is not performant, we can re-do the calculations and the underlying data model as needed to make this performant.

**Comment by JohnMwashuma** [comment]
So for turn out report this is how i will implement it:

From the `station` model i can get `result forms` associated with that `station`, on each `result form` i will check if it has a `recon form` so that i can use that to check the `number of ballots used`.

Afterwards i will sum up the `total number of ballots used` in that particular `station` which will then translate to the turn out in that particular `station`.

Using the station model i can also get the `center, sub constituency, and gender`.

I will then use this data to build a table that will contain the `total turnout per station` (total number of ballots used) and also display the `center, sub constituency, and gender` for each `station`.

I will try and build a query set for this instead of looping through the data using `for loops` which can be expensive.

@pld @akahure Does this make sense to you?

**Comment by JohnMwashuma** [comment]
@pld  for number 2, `Center/station completion`, we currently show `center and office progress reports` where we show `number of forms processed per form state` and their `percentage` which is `number of forms in a particular stage` divided by `total forms in that tally`.

What's missing is the Station progress, so maybe if we add this to that module, that might be it for this requirement.

Here is the view file for this module:
https://github.com/onaio/tally-ho/blob/master/tally_ho/apps/tally/views/reports/offices.py

**Comment by JohnMwashuma** [comment]
For `office progress report module` which is currently there as mentioned above, i will have to add a new column of `valid votes per office` in the current table.

**Comment by JohnMwashuma** [comment]
`Nice to access for only user` i also do not understand this, @akahure any idea?

**Comment by pld** [comment]
I think this all makes sense to me, can you split this into multiple issues? After we've clarified scope here we should pick off the sub-issues and work on them separately

**Comment by JohnMwashuma** [comment]
Yes am gonna do that

**Comment by JohnMwashuma** [comment]
Going to close this issue, all results reporting requirements will be addressed on this https://github.com/onaio/tally-ho/issues/279
