### ISSUE TITLE
Process discrepancy report

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#303]
### Current requirement functionality
---
*This functionality does not exists in the current software.*

### User story
---
List of polling stations/centres under process audit (based on constituency/HNEC field
office/province)
List of polling station/centres under investigation & field verification (based
constituency/HNEC field office/province)
List of polling stations/centres excluded after investigations (based constituency/HNEC
field office/province)
### Implementation plan
---
- [ ] For List of polling stations/centres under process audit:
          - Build out a list of polling stations/centres with result forms in audit state based on office.
- [ ] For List of polling station/centres under investigation & field verification (based
constituency/HNEC field office/province): Not clear at the moment.
- [ ] For List of polling stations/centres excluded after investigations (based constituency/HNEC
field office/province): Not clear at the moment.

**Comment by JohnMwashuma** [comment]
Need clarification on what `station/centres under investigation & field verification` and `polling stations/centres excluded after investigations` mean.

**Comment by JohnMwashuma** [comment]
Related to https://github.com/onaio/tally-ho/issues/279

**Comment by JohnMwashuma** [comment]
> Need clarification on what `station/centres under investigation & field verification` and `polling stations/centres excluded after investigations` mean.

station/centres under investigation means, inactive ones and stations/centres excluded after investigations means those ones which were initially active but are currently active.

**Comment by pld** [comment]
https://github.com/onaio/tally-ho/pull/314
