### ISSUE TITLE
Presentation exporter

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#357]
#### Task check list
---
- [ ] Add Race type filter for filtering final results by Race type.
- [ ] Add center and station filters for excluding selected centers and stations from final results.
- [ ] Add PDF export option for exporting a configurable number of leading candidates.
- [ ] Create a configuration option of number of leading candidates to export per race type.
- [ ] Add number of processed forms per race filter option, that display all results for races where x number of forms have been processed.
- [ ] Add power point export option for results based on the above applied filters.
- [ ] Add overall stats on the results export page, such as for each race type display:
     - [ ] Expected number of processed forms, forms processed and percentage of processed forms.
