### ISSUE TITLE
Add Race type filter for filtering final results by Race type.

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#358]
### Task check list
---
- [ ] Add a filtering section on the form results [template](https://github.com/onaio/tally-ho/blob/6f1721008b2519890563a8284a1ebd8ab1fca41c/tally_ho/apps/tally/templates/reports/form_results.html) for filtering results by race types. Inside the filtering section create the following components:
     - [ ] A multiple select dropdown list of tally [race types ](https://github.com/onaio/tally-ho/blob/647126fbc2c5671d19a6944da4375769a35166ab/tally_ho/libs/models/enums/race_type.py).
     - [ ] An `Apply` button with some guidance text that says `Filter results by race`.
- [ ] Create an onclick event listener for the `Apply` button similar to [this](https://github.com/onaio/tally-ho/blob/7b5175dc09bc22cf6811240b75465efa110be94d/tally_ho/apps/tally/static/js/data_table.js#L70) that will be used to send an Ajax request to this [django view](https://github.com/onaio/tally-ho/blob/5fb8d72000beb3517b9f2598de0f102e7c512ccd/tally_ho/apps/tally/views/reports/administrative_areas_reports.py#L3061) for filtering the results by the selected race type. Ignore the [else block](https://github.com/onaio/tally-ho/blob/7b5175dc09bc22cf6811240b75465efa110be94d/tally_ho/apps/tally/static/js/data_table.js#L85) in this implementation.
- [ ] Update the Django view [filter_queryset](https://github.com/onaio/tally-ho/blob/5fb8d72000beb3517b9f2598de0f102e7c512ccd/tally_ho/apps/tally/views/reports/administrative_areas_reports.py#L3092) method that filters results, to also filter results by race type when available. The filtering logic, should be applied on this [results_queryset](https://github.com/onaio/tally-ho/blob/5fb8d72000beb3517b9f2598de0f102e7c512ccd/tally_ho/apps/tally/views/reports/administrative_areas_reports.py#L509) function inside this [if block](https://github.com/onaio/tally-ho/blob/5fb8d72000beb3517b9f2598de0f102e7c512ccd/tally_ho/apps/tally/views/reports/administrative_areas_reports.py#L553).

### Related to
---
https://github.com/onaio/tally-ho/issues/357
