### ISSUE TITLE
Add center and station filters for filtering final results by center and station.

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#360]
### Task check list
---
- [x] Add a filtering section on the form results [template](https://github.com/onaio/tally-ho/blob/6f1721008b2519890563a8284a1ebd8ab1fca41c/tally_ho/apps/tally/templates/reports/form_results.html) for filtering results by center and station. Inside the filtering section create the following components:
     - [x] A multiple select drop-down list of [centers](https://github.com/onaio/tally-ho/blob/6f1721008b2519890563a8284a1ebd8ab1fca41c/tally_ho/apps/tally/templates/reports/form_results.html#L31) and [stations](https://github.com/onaio/tally-ho/blob/6f1721008b2519890563a8284a1ebd8ab1fca41c/tally_ho/apps/tally/templates/reports/form_results.html#L39).
     - [x] An `Apply` button with some guidance text that says `Filter results by center(s) and station(s)`.
- [x] Create an `on-change` event listener for the `centers` select list similar to [this](https://github.com/onaio/tally-ho/blob/85e3cb65564086952a204c725a5d08e9e38e9045/tally_ho/apps/tally/static/js/get_centers_stations.js#L2) that will be used to auto select the stations id's that belong to the selected [centers](https://github.com/onaio/tally-ho/blob/85e3cb65564086952a204c725a5d08e9e38e9045/tally_ho/apps/tally/static/js/get_centers_stations.js#L2). The on-change listener makes an Ajax request to this [get_centers_stations](https://github.com/onaio/tally-ho/blob/5fb8d72000beb3517b9f2598de0f102e7c512ccd/tally_ho/apps/tally/views/reports/administrative_areas_reports.py#L1363) function that retrieves a center's station id's.
- [x] Create an `on-click` event listener for the `Apply` button similar to [this](https://github.com/onaio/tally-ho/blob/7b5175dc09bc22cf6811240b75465efa110be94d/tally_ho/apps/tally/static/js/data_table.js#L70) that will be used to send an Ajax request to this [django view](https://github.com/onaio/tally-ho/blob/5fb8d72000beb3517b9f2598de0f102e7c512ccd/tally_ho/apps/tally/views/reports/administrative_areas_reports.py#L3061) for filtering the results by the selected center and station id. Ignore the [else block](https://github.com/onaio/tally-ho/blob/7b5175dc09bc22cf6811240b75465efa110be94d/tally_ho/apps/tally/static/js/data_table.js#L85) in this implementation.
- [x] Update the Django view [filter_queryset](https://github.com/onaio/tally-ho/blob/5fb8d72000beb3517b9f2598de0f102e7c512ccd/tally_ho/apps/tally/views/reports/administrative_areas_reports.py#L3092) method that filters results, to also filter results by selected center and station when available.

### Related to
---
https://github.com/onaio/tally-ho/issues/357
