### ISSUE TITLE
 Add PDF/Powerpoint export option for exporting a configurable number of leading candidates results in PDF format.

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#362]
### User story
---
Create pdf and power point button's on the form results page for exporting candidates results based on the filters applied.

### Task check list
---
- [x] Add a Results Export section on the form results [template](https://github.com/onaio/tally-ho/blob/6f1721008b2519890563a8284a1ebd8ab1fca41c/tally_ho/apps/tally/templates/reports/form_results.html) for exporting results in pdf and powerpoint formats. Inside this section create the following components:
    - [x] A select dropdown with a range of leading candidates to be exported. Ranges should be:
        - 10, 25, 50, 100, 500.
    - [x] An `Export to PDF` button and `Export to Powerpoint` button.
- [x] Create an on-click event listener on the buttons similar to this [one](https://github.com/onaio/tally-ho/blob/e50dcb674b6ce18d722dd3bc3cdca13aa71e4e3a/tally_ho/apps/tally/static/js/download_centers_and_stations_list.js#L13) that will be used to send an Ajax request for filtering the results by the specified range of leading candidate's and other filters that have been applied.
- [x] The PDF/Powerpoint Export will consist of the following components:
     - [x] A page header and footer based on HNEC design.
     - [x] A report header section showing the filters applied before the export.
     - [x] A table with the list of candidates results.

### Related to
---
https://github.com/onaio/tally-ho/issues/357

**Comment by lincmba** [comment]
Closed by https://github.com/onaio/tally-ho/pull/405
