### ISSUE TITLE
Create an overall results statistics section on the results export page based on applied filters.

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#363]
### Task check list
---
- [ ] Create an overall results statistics section on the form results [template](https://github.com/onaio/tally-ho/blob/6f1721008b2519890563a8284a1ebd8ab1fca41c/tally_ho/apps/tally/templates/reports/form_results.html) for displaying the overall results based on applied filters. This section will take the structure of a table with the following columns:
    - Expected number of processed forms.
    - Forms processed.
    - Percentage of processed forms.
- [ ] Create a `Generate Overall Report` button that upon click triggers an AJax request which take's the all the applied filter's specifically, selected centers, stations and race type's then calculates queries the overall results. For the query set use the following logic:
   - [ ] Filter the Result form [model](https://github.com/onaio/tally-ho/blob/c0296abee1af228cdaf46f0cf0f49cd5f489dea9/tally_ho/apps/tally/models/result_form.py#L135-L136) by the applied filters to get the number of forms processed. Also apply where form_state is ARCHIVED.
   - [ ] Filter the Result form [model](https://github.com/onaio/tally-ho/blob/c0296abee1af228cdaf46f0cf0f49cd5f489dea9/tally_ho/apps/tally/models/result_form.py#L135-L136) by distinct and tally id to get the expected number of processed forms. Check an example [here](https://github.com/onaio/tally-ho/blob/b9c9fa0c416d6175c02310d800f5c9ff52e01290/tally_ho/libs/reports/progress.py#L71).
   - [ ] Divide the the forms processed by the expected number of processed to get the percentage number of forms processed. Check an example [here](https://github.com/onaio/tally-ho/blob/b9c9fa0c416d6175c02310d800f5c9ff52e01290/tally_ho/libs/reports/progress.py#L125).

#### Related to
---
https://github.com/onaio/tally-ho/issues/357

**Comment by JohnMwashuma** [comment]
Duplicate issue https://github.com/onaio/tally-ho/issues/369
