### ISSUE TITLE
Add sub constituency code column to the candidates final results report

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#367]
#### Task check list
---
- [x] Rename `Voting District` column to `Sub Constituency Code` in the form results [template](https://github.com/onaio/tally-ho/blob/6f1721008b2519890563a8284a1ebd8ab1fca41c/tally_ho/apps/tally/templates/reports/form_results.html) table.
- [x] Rename the `voting_district` column to `sub_con_code` in the [columns property](https://github.com/onaio/tally-ho/blob/5fb8d72000beb3517b9f2598de0f102e7c512ccd/tally_ho/apps/tally/views/reports/administrative_areas_reports.py#L3067) of the `ResultFormResultsListDataView` class view.
- [x] Replace all occurrences of `voting_district` with `sub_con_code` in the [results_queryset](https://github.com/onaio/tally-ho/blob/5fb8d72000beb3517b9f2598de0f102e7c512ccd/tally_ho/apps/tally/views/reports/administrative_areas_reports.py#L509) function.
