### ISSUE TITLE
Make default site Language configurable and fix site translation

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#371]
### User story
---
Ensure that Arabic Language is in place throughout the system and Arabic language is the default one for particular deployments. 

### Acceptance Criteria
---
- [ ] Default site language should be configurable per deployment.
- [ ] One should be able to translate a page based on the language selected.

### Task check list
---
- [ ] Make [LANGUAGE_CODE](https://github.com/onaio/ansible-tally-ho/blob/9167abcb2c69830e2dea6def98996b32334bd596/templates/checkoutpath/tally_ho/config/settings.py.j2#L68) Django settings configurable and pass appropriate value on ansible inventories group var's.
- [ ] Update [locale](https://github.com/onaio/tally-ho/blob/a3e3850173cf6a8a344c1ee5b37adf814550d260/tally_ho/libs/utils/context_processors.py#L34) function to the following:
```python
def locale(request):
    locale = request.session.get('locale') or getattr(
        settings, "LANGUAGE_CODE", None)
    if locale and translation.check_for_language(locale):
        translation.activate(locale)
    return {"locale": locale}
```
- [ ] Make sure all magic strings are wrapped in translation.
- [ ] Remake locale messages using `python manage.py makemessages -l ar`
- [ ] Translate the `msgid` property inside the django.po file where the `msgstr` is `msgstr ""` to Arabic and recompile the messages using `python manage.py compilemessages`
- [ ] Make datatables language definitions dynamic based on the current locale/language code.

**Comment by faith-mutua** [comment]
@JohnMwashuma the [login page](https://tallyho.onalabs.org/) loads with Arabic set as the default language. A user is able to translate the pages without any problem.
