### ISSUE TITLE
Break up final candidates results report into separate pages per election type.

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#373]
### Context
---
Currently the final candidates results are being displayed on one table which grows exponentially as more forms get processed. This then increases the Ajax request size to server the table data and UWSGI fails with a buffer size exceeded error. Although the buffer size can be increased, this is not a sustainable solution since we could easily exceed the max buffer size.

### Suggested solution
---
Split the final candidates results report into separate pages per election types i.e. split the reports into presidential and parliamentary report types. One can then filter by race type in case the election type has more than one Race type.

### Acceptance Criteria
---
- [ ] Candidates final results reports should in different pages based on the election type.
- [ ] If the above report has more than one Race type, one should be able to filter by race type. 
- [ ] The UWSGI error should not be encountered as more forms get ARCHIVED for different election types i.e. all the reports should load successfully.

### Task check list
---
- [ ] Break up the final candidates results page into two pages. These pages will be one for the Presidential election type and the other for the Parliamentary election type.
- [ ] Enable filtering by race type if the election supports more than one race type.
