### ISSUE TITLE
Update the tally system to handle new Ballot types more generically

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#374]
### User story
---
Currently the tally system supports 3 ballot types and can support new ballot types but with the following constraints:

  - Updating of the initial tally creation files in a particular format to take into account the new ballots.
  - Refactoring the tally app to accommodate the new ballot types.
  
This is not the desired workflow as it is prone to human errors and a longer feedback loop between the client and the devs. That said, we need a more generic solution that can configurable per deployment and handle a variety of Ballot types without the above mentioned constraints.

### Proposed solution
---
- A Race Django model will be used to hold Race types. This model will be populated by a configurable list of Race types from the Django settings so that in case we have new one's, they will just be updated on deployment.
- Race creation will upon a deployment via a Django management command executed during the deployment.
- The configurable list of Races will consist of:
   - Race Type
   - Race Code
   - Ballot Name. **NB** This should be similar to the Ballot Number column name in the sub constituency file.
- The Ballot model will be updated to have a Many to 1 relationship with the Race model for assignment of Races to Ballots.
   - With this change the current  `race_type` property on Ballot Model will be retrieved from the Race Model hence this property will be removed from the model.
-  Refactor the tally app to use Race Model where it's currently using the Races Enum.

### Acceptance Criteria
---
- [ ] Races should be configurable from a config file. Django settings.
- [ ] Configured Races should be created/updated through a deployment.

### Task check list
---
- [ ] Create a Race Model with the following properties:
   - type = string
   - code = number
   - ballot_name = string
- [ ] Create an Environment variable called Races which will be an Array of race type dictionaries with the following properties:
    - type
   - code
   - ballot_name
- [ ] Create a `create_races` Django management command that will pick the current configure RACES and create Race objects.
- [ ] Update the tallyho ansible role to always to always run the `create_races` Django management command. The command can be added to this [list](https://github.com/onaio/ansible-tally-ho/blob/d77a6fa2cc9ac062f9a19d62018ae2b7c884008b/defaults/main.yml#L143).
- [ ] Refactor the tally app to use Race Model where it's currently using the Races Enum.

**Comment by JohnMwashuma** [comment]
Nice! makes sense.
