### ISSUE TITLE
Fix tallyho ansible deployment scripts due to role updates

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#398]
### Task check list
---
- [ ] Update [ona ansible django role](https://github.com/onaio/ansible-django) to check if the uwgis array variable has been set and has items
- [ ] Rename/Fix Django restart service handler on [tallyho ansible role](https://github.com/onaio/ansible-tally-ho).
- [ ] Update tallyho ansible group vars.

**Comment by JohnMwashuma** [comment]
Closed by the following prs:
- https://github.com/onaio/ansible-django/pull/47
- https://github.com/onaio/ansible-tally-ho/pull/15
- https://github.com/onaio/infrastructure/pull/7000
