### ISSUE TITLE
Update Progressive Report

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#400]
### Context
---
The progressive report is used for displaying candidates votes per administrative area. Administrative areas are Regions, Constituencies and Sub Constituencies.

### Proposed changes
---
- [ ] Create filter drop-downs for filtering the report per the Administrative area's selected. The Administrative areas list will be based on the one's that have result forms in archived state. The filters will in the following exact order:
   - Regions.
   - Constituencies.
   - Sub Constituencies.
- [ ] Selecting region's should update the Constituencies and Sub Constituencies list with the one's in the region's selected.
- [ ] The progressive report will consist of the following columns:
   - Administrative area
   - Number of candidates
   - Number of votes
   - Action
 - [ ] The `Administrative area` column value's should be the last Administrative Area selected so that we can display the progressive report per Administrative Area i.e.
    - On initial page load, no filter would have been selected so the report will be showing progressive report per region(s).
    - If a region(s) is selected, the report will still show progressive report per the selected regions.
    - If a constituenciey(s) is selected, the report will still show progressive report per the selected constituenciey(s).
    - If a sub constituenciey(s) is selected, the report will still show progressive report per the selected sub constituenciey(s).
- [ ] The `Action` column will have a button that reads `Votes per candidate` which when clicked should redirect to a screen that shows candidates with at least one vote and their respective votes. This screen will consist of the following columns:
     - Candidates name
     - Votes
   **NB:**  For sub consitutuency candidates votes list it should be order by ballot order (candidate order field).
 
### Task check list
---
- [ ] Create filter drop-downs for filtering the report per the Administrative area's. The filters will the following in the exact order:
   - Regions.
   - Constituencies.
   - Sub Constituencies.
   
   The following Django queries should help with logic:
   ```python
   processed_region_names = list(ResultForm.objects.filter(tally=tally).values_list('center__region', flat=True).distinct())

  selected_constuencies_names_by_regions = list(ResultForm.objects.filter(tally=tally, center__region__in=processed_region_names).values_list('center__constituency__name',flat=True).distinct())

  selected_sub_constuencies_codes_by_regions = list(ResultForm.objects.filter(tally=tally, center__region__in=processed_region_names).values_list('center__sub_constituency__code', flat=True).distinct())
   ```
- [ ] Create a progressive report per Administrative area(s) selected. The following Django queries will help with this logic:

     Regions progressive report:

    ```python
    from tally_ho.libs.utils.query_set_helpers import Round

    processed_region_names = list(ResultForm.objects.filter(tally=tally).values_list('center__region', flat=True).distinct())

    admin_area_column_name = 'result_form__center__region'

    Result.objects.filter(result_form__tally=tally, result_form__form_state=FormState.ARCHIVED, entry_version=EntryVersion.FINAL, result_form__center__region__in=processed_region_names).annotate(admin_area=F(admin_area_column_name)).values('admin_area').annotate(num_candidates=Count('candidate__id'), num_votes=Sum('votes'))

    ```
    Regions progressive report (candidate's votes report based on the selected region name)
   
   ```python
   selected_region_name = '<region_name>'
   
   Result.objects.filter(result_form__tally=tally, result_form__form_state=FormState.ARCHIVED, entry_version=EntryVersion.FINAL, votes__gt=0, result_form__center__region=selected_region_name).annotate(candidate_name=F('candidate__full_name'), candidate_votes=F('votes')).values('candidate_name', 'candidate_votes')

   ```
   Constituencies progressive report:

    ```python
    from tally_ho.libs.utils.query_set_helpers import Round
  
    selected_constuencies_names_by_regions = list(ResultForm.objects.filter(tally=tally, center__region__in=processed_region_names).values_list('center__constituency__name',flat=True).distinct())

    admin_area_column_name = 'result_form__center__constituency__name'

    Result.objects.filter(result_form__tally=tally, result_form__form_state=FormState.ARCHIVED, entry_version=EntryVersion.FINAL, result_form__center__region__in=processed_region_names, result_form__center__constituency__name__in=selected_constuencies_names_by_regions).annotate(admin_area=F(admin_area_column_name)).values('admin_area').annotate(num_candidates=Count('candidate__id'), num_votes=Sum('votes'))
    ```
    Constituencies progressive report (candidate's votes report based on the selected region name and constituency name)
   
   ```python
   selected_region_name = '<region_name>'
   selected_constituency_name = '<constituency_name>'
   
   Result.objects.filter(result_form__tally=tally, result_form__form_state=FormState.ARCHIVED, entry_version=EntryVersion.FINAL, votes__gt=0, result_form__center__region=selected_region_name, result_form__center__constituency__name=selected_constituency_name).annotate(candidate_name=F('candidate__full_name'), candidate_votes=F('votes')).values('candidate_name', 'candidate_votes')

   ```
    Sub constituencies progressive report:

    ```python
    from tally_ho.libs.utils.query_set_helpers import Round
  
    selected_sub_constuencies_codes_by_regions = list(ResultForm.objects.filter(tally=tally, center__region__in=processed_region_names).values_list('center__sub_constituency__code',flat=True).distinct())

    admin_area_column_name = 'result_form__center__sub_constituency__code'

    Result.objects.filter(result_form__tally=tally, result_form__form_state=FormState.ARCHIVED, entry_version=EntryVersion.FINAL, result_form__center__region__in=processed_region_names, result_form__center__constituency__name__in=selected_constuencies_names_by_regions, result_form__center__sub_constituency__code__in=selected_sub_constuencies_codes_by_regions).annotate(admin_area=F(admin_area_column_name)).values('admin_area').annotate(num_candidates=Count('candidate__id'), num_votes=Sum('votes'))
    ```
   Sub constituencies progressive report (candidate's votes report based on the selected region name, constituency name and sub constituency code. Ordered by ballot order)
   
   ```python
   selected_region_name = '<region_name>'
   selected_constituency_name = '<constituency_name>'
   selected_sub_constituency_code = '<constituency_name>'
   
   Result.objects.filter(result_form__tally=tally, result_form__form_state=FormState.ARCHIVED, entry_version=EntryVersion.FINAL, votes__gt=0, result_form__center__region=selected_region_name, result_form__center__constituency__name=selected_constituency_name, result_form__center__sub_constituency__code=selected_sub_constituency_code).annotate(candidate_name=F('candidate__full_name'), candidate_votes=F('votes')).values('candidate_name', 'candidate_votes').order_by('candidate__order')

   ```

- [ ] Update the `ProgressiveReportDataView` view `filter_queryset` method with the above logic
