### ISSUE TITLE
Update Candidates results report title and the table columns.

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#403]
### Task check list
---
- [ ] Rename the link to the Candidates results report from [Result Form List](https://tallyho.onalabs.org/super-administrator/form-results/1/) to `Candidates results`.
- [ ] Rename the report title from `Form Results` to `Candidates results`.
- [ ] For the table columns, the following updates should be made:
    - [ ] Add `Releasable` column which will hold the value of `Available for release` in ballots.
    - [ ] Remove `Race Number` since it's the same as the `Ballot Number` column.
    - [ ] Rename `Ballot` column to `Ballot Number`.
    - [ ] Full column list will then be
        - Candidate Name
        - Candidate Valid Votes
        - Total Invalid Ballots
        - Total Valid Votes
        - Registrants
        - Race Type
        - Region
        - Center
        - Station ID
        - Station Number
        - Releasable
        - Candidate Status
        - Office
        - Barcode
        - Gender
        - Sub Constituency Code
        - Order
        - Unstamped Ballots
        - Cancelled Ballots
        - Spoilt Ballots
        - Unused Ballots
        - Number of Signatures
        - Received Ballots Papers
        - Ballot Number
