### ISSUE TITLE
Update Candidate's results report filters

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#406]
### User story
---
A user should be able to filter candidates votes results by:
 - Races with ballots marked as releasable.
 - Races with a user-entered/user defined % of polling stations processed. 
 - Include/Exclude Stations tabulated from releasable races.
 - All candidates, Active or a pre-determined number of leading candidates.

In total the candidates results report will have filters in the following order:
- All/Available for release/Not available for release Ballot Status
- Races.
- User defined % of polling stations processed per Race(s) **(default 0: meaning no percentage applied).**
- Centers.
- Station Status
- Stations.
- All/Active/InActive Candidates.
- Pre-determined number of leading candidates **(default 0: meaning no pre-determined number applied).**

### Task check
---
- [x] Enable filtering results by station id's without the need to select other filters e.g. centers. Related to: https://github.com/onaio/tally-ho/issues/359
- [x] Create a `Ballot Status` filter drop down for filtering results. The options should include:
   - [x] All (All ballots)
   - [x] Available for release (ballots where the `available_for_release` field is true)
   - [x] Not available for release (ballots where the `available_for_release` field is false)
- [x] Create a `Station Status` filter drop down for filtering results. The options should include:
   - [x] All (All stations)
   - [x] Active (stations where the `active` field is true)
   - [x] In Active (stations where the `active` field is false)
- [x] Create an input field filter for percentage of polling stations processed per race(s) selected with a default value of 0 **(0 meaning it has not been applied)**. When applied the following should happen:
   - [x] Updates retrieval logic for stations and centers filter options to the following:
       - Get stations assigned to the selected races, use the center field and get the respective results forms then filter by ballot race.
       - Group by station id and count the total result forms assigned, total result forms assigned and in `ARCHIVE` form state and station processed percentage which will be **forms in archive/total result forms * 100**.
       - Filter the above results where the calculated `station processed percentage` is equal or greater than the user defined station processed percentage and return the station id's and center id's.
       - The actual queryset
       ```python
       stations_processed_percentage = <user_input>
       qs = Station.objects.filter(
        tally__id=tally.id,
        center__resultform__ballot__race_type=RaceType.PRESIDENTIAL
          ).values('id').annotate(
        total_result_forms=Count(
            'center__resultform__barcode',
            distinct=True
        ),
        total_result_forms_archived=Count(
            'center__resultform__barcode',
            distinct=True,
            filter=Q(center__resultform__form_state=FormState.ARCHIVED)
        ),
        processed_percentage=Round(
            100 * F('total_result_forms_archived')/F('total_result_forms'),
            digits=2
        )).filter(
            processed_percentage__gte=stations_processed_percentage).values(
                'id')
       station_ids = [item.get('id') for item in qs]
       ```
- [x] Create a filter drop down for all candidates, active and inactive candidates. When applied filter the results where the `Candidate` model field `active` is set to the applied value.
- [x] Set the default value of number of leading candidates filter to 0.  **(0: meaning no pre-determined number applied).**

### Acceptance criteria
---
A user should be able to filter candidates votes results by:
 - [ ] Races with ballots marked as releasable.
 - [ ] Races with a user-entered/user defined % of polling stations processed. 
 - [ ] Include/Exclude Stations tabulated from releasable races.
 - [ ] All candidates, Active or a pre-determined number of leading candidates.
