### ISSUE TITLE
Progress of running elections by Sub Race Report

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#410]
### Context
---
The Progress Report feature aims to generate a table report that displays the forms processed vs all forms expected per sub-race type for each administrative area. The report can be generated per region, office, constituency, or sub-constituency

### Requirements
---
- Tabs:
     - Create report tabs on the progress report that will be used for viewing each report separately. The tabs will be based on the administrative areas and named as follows:
        - Region’s Progress Report.
        - Office’s Progress Report.
        - Constituencies Progress Report.
        - Sub Constituencies Progress Report.
    - When a tab is clicked the system should display the respective administrative area progress report and also make the current tab active.
- Report tables:
    - The Administrative area progress report tables should include the following columns:
        - Regions/Office/Constituency/Sub-Constituency
        - Presidential
        - %
        - General
        - %
        - Women
        - %
        - Overall
        - %
- The last row in each of the reports should be a Total of each of the respective column values.
- CSV Export:
    - Enable the report to be exportable in CSV format.

### Task check list
---
- [ ] Create a html template view that has following bootstrap tabs:
     - Region’s Progress Report.
     - Office’s Progress Report.
     - Constituencies Progress Report.
     - Sub Constituencies Progress Report.
- [ ] Each of the above tab should be associated with their own unique table that is displayed upon clicking the tab. The tables will include the following columns:
    - Regions/Office/Constituency/Sub-Constituency
    - Presidential
    - %
    - General
    - %
    - Women
    - %
    - Overall
    - %
- [ ] Create initialize a datatables table for each table by targeting the table's unique id tag. This script can be placed on the `{% block javascript %}` on the html template wrapped with the `<script></script>` tags.
- [ ] Create the following functional views:
    - [ ] progress_render_view: for rendering the html template, this will also pass the initial context data required e.g. report ajax urls
    - [ ] regions_progress_report_view: will be used for getting regions report data. The ajax request for getting regions progress should use this view endpoint.
    - [ ] offfices_progress_report_view: will be used for getting regions report data. The ajax request for getting offices progress should use this view endpoint.
    - [ ] constituencies_progress_report_view: will be used for getting regions report data. The ajax request for getting constituencies progress should use this view endpoint.
    - [ ] sub_constituencies_progress_report_view: will be used for getting regions report data. The ajax request for getting sub_constituencies progress should use this view endpoint.
- [ ] Enable navigating to the next page and back if the report has more than one page of records to show.
- [ ] Enable page size changes.
- [ ] Add total row as the last row in the reports.
- [ ] Enable csv export.
   
### Acceptance criteria
---
- [ ] The progress report table is generated accurately based on the selected administrative area tab.
- [ ] The progress report table includes the specified columns.
- [ ] The progress report can be exported and printed as a CSV.

**Comment by JohnMwashuma** [comment]
Working skeleton implementation of these reports https://github.com/onaio/tally-ho/pull/411

**Comment by JohnMwashuma** [comment]
https://github.com/onaio/tally-ho/pull/411
